name: Release Application

on:
  push:
    branches:
      - "**"

env:
  OPENSHIFT_SERVER: "https://api.sandbox-m4.g2pi.p1.openshiftapps.com:6443"
  OPENSHIFT_NAMESPACE: "aernouthoebreckx-dev"

jobs:
  deploy:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/tst'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      - name: Apply Openshift YAML
        run: |
          kubectl apply -f openshift.yaml -n $OPENSHIFT_NAMESPACE
